[package]
name = "Rustle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ariadne = "0.4.1"
clap = { version = "4.4.4", features = ["derive"] }
nom = "7.1.3"
unsvg = "1.2.1"
